package app.entity;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Analyse generated by hbm2java
 */
public class Analyse  implements java.io.Serializable {


     private Integer id;
     private DossierLab dossierLab;
     private String description;
     private Date date;

    public Analyse() {
    }

    public Analyse(DossierLab dossierLab, String description, Date date) {
       this.dossierLab = dossierLab;
       this.description = description;
       this.date = date;
    }

    public Analyse(String description, Date date) {
        this.date = date;
        this.description = description;
    }

    public Analyse(int id, DossierLab dossierLab, String description, Date date) {
        this.id = id;
        this.dossierLab = dossierLab;
        this.description = description;
        this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DossierLab getDossierLab() {
        return this.dossierLab;
    }
    
    public void setDossierLab(DossierLab dossierLab) {
        this.dossierLab = dossierLab;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
}


