package app.entity;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DossierLab generated by hbm2java
 */
public class DossierLab  implements java.io.Serializable {


     private Integer id;
     private Laboratoire laboratoire;
     private Patient patient;
     private Set analyses = new HashSet(0);

    public DossierLab() {
    }

	
    public DossierLab(Laboratoire laboratoire, Patient patient) {
        this.laboratoire = laboratoire;
        this.patient = patient;
    }
    
    public DossierLab(int id ,Laboratoire laboratoire, Patient patient) {
        this.id = id;
        this.laboratoire = laboratoire;
        this.patient = patient;
    }
    
    public DossierLab(Laboratoire laboratoire, Patient patient, Set analyses) {
       this.laboratoire = laboratoire;
       this.patient = patient;
       this.analyses = analyses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Laboratoire getLaboratoire() {
        return this.laboratoire;
    }
    
    public void setLaboratoire(Laboratoire laboratoire) {
        this.laboratoire = laboratoire;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Set getAnalyses() {
        return this.analyses;
    }
    
    public void setAnalyses(Set analyses) {
        this.analyses = analyses;
    }




}


