package app.entity;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FicheMedicale generated by hbm2java
 */
public class FicheMedicale  implements java.io.Serializable {


     private Integer id;
     private Dossier dossier;
     private Maladie maladie;
     private String remarque;
     private Date date;
     private String description;
     private Set medicaments = new HashSet(0);

    public FicheMedicale() {
    }

	
    public FicheMedicale(Dossier dossier, Date date) {
        this.dossier = dossier;
        this.date = date;
    }
    public FicheMedicale(Dossier dossier, Maladie maladie, String remarque, Date date, String description, Set medicaments) {
       this.dossier = dossier;
       this.maladie = maladie;
       this.remarque = remarque;
       this.date = date;
       this.description = description;
       this.medicaments = medicaments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dossier getDossier() {
        return this.dossier;
    }
    
    public void setDossier(Dossier dossier) {
        this.dossier = dossier;
    }
    public Maladie getMaladie() {
        return this.maladie;
    }
    
    public void setMaladie(Maladie maladie) {
        this.maladie = maladie;
    }
    public String getRemarque() {
        return this.remarque;
    }
    
    public void setRemarque(String remarque) {
        this.remarque = remarque;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getMedicaments() {
        return this.medicaments;
    }
    
    public void setMedicaments(Set medicaments) {
        this.medicaments = medicaments;
    }




}


