package app.entity;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Laboratoire generated by hbm2java
 */
public class Laboratoire implements java.io.Serializable {

    private int id;
    private User user;
    private int numService;
    private String nom;
    private Date horaireDebut;
    private Date horaireFin;
    private Integer note;
    private Set rendezvouses = new HashSet(0);
    private Set services = new HashSet(0);
    private Set events = new HashSet(0);
    private Set dossierLabs = new HashSet(0);

    public Laboratoire() {
    }

    public Laboratoire(int id, User user, int numService, String nom, Date horaireDebut, Date horaireFin, Set services) {
        this.id = id;
        this.user = user;
        this.numService = numService;
        this.nom = nom;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
        this.services = services;
    }

    public Laboratoire(int id, User user, int numService, String nom, Date horaireDebut, Date horaireFin, Integer note) {
        this.id = id;
        this.user = user;
        this.numService = numService;
        this.nom = nom;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
        this.note = note;
    }

    public Laboratoire(User user, int numService, String nom, Date horaireDebut, Date horaireFin) {
        this.user = user;
        this.numService = numService;
        this.nom = nom;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
    }

    public Laboratoire(int id, User user, int numService, String nom, Date horaireDebut, Date horaireFin) {
        this.id = id;
        this.user = user;
        this.numService = numService;
        this.nom = nom;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
    }

    public Laboratoire(int id, User user, int numService, String nom, Date horaireFin) {
        this.id = id;
        this.user = user;
        this.numService = numService;
        this.nom = nom;
        this.horaireFin = horaireFin;
    }

    public Laboratoire(int id) {
        this.id = id;
    }

    public Laboratoire(User user, int numService, String nom, Date horaireDebut, Date horaireFin, Integer note, Set rendezvouses, Set services, Set events, Set dossierLabs) {
        this.user = user;
        this.numService = numService;
        this.nom = nom;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
        this.note = note;
        this.rendezvouses = rendezvouses;
        this.services = services;
        this.events = events;
        this.dossierLabs = dossierLabs;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public int getNumService() {
        return this.numService;
    }

    public void setNumService(int numService) {
        this.numService = numService;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public Date getHoraireDebut() {
        return this.horaireDebut;
    }

    public void setHoraireDebut(Date horaireDebut) {
        this.horaireDebut = horaireDebut;
    }

    public Date getHoraireFin() {
        return this.horaireFin;
    }

    public void setHoraireFin(Date horaireFin) {
        this.horaireFin = horaireFin;
    }

    public Integer getNote() {
        return this.note;
    }

    public void setNote(Integer note) {
        this.note = note;
    }

    public Set getRendezvouses() {
        return this.rendezvouses;
    }

    public void setRendezvouses(Set rendezvouses) {
        this.rendezvouses = rendezvouses;
    }

    public Set getServices() {
        return this.services;
    }

    public void setServices(Set services) {
        this.services = services;
    }

    public Set getEvents() {
        return this.events;
    }

    public void setEvents(Set events) {
        this.events = events;
    }

    public Set getDossierLabs() {
        return this.dossierLabs;
    }

    public void setDossierLabs(Set dossierLabs) {
        this.dossierLabs = dossierLabs;
    }

}
