package app.entity;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Maladie generated by hbm2java
 */
public class Maladie  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private Set ficheMedicales = new HashSet(0);

    public Maladie() {
    }

	
    public Maladie(String nom) {
        this.nom = nom;
    }
    public Maladie(String nom, Set ficheMedicales) {
       this.nom = nom;
       this.ficheMedicales = ficheMedicales;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getFicheMedicales() {
        return this.ficheMedicales;
    }
    
    public void setFicheMedicales(Set ficheMedicales) {
        this.ficheMedicales = ficheMedicales;
    }




}


