package app.entity;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1



/**
 * Reponse generated by hbm2java
 */
public class Reponse  implements java.io.Serializable {

   private Integer id;
     private Medecin medecin;
     private Question question;
     private String text;

    public Reponse() {
    }

    public Reponse(Medecin medecin, Question question, String text) {
       this.medecin = medecin;
       this.question = question;
       this.text = text;
    }

      public Reponse(int id,Question question,String text) {
          this.id=id ;
          this.question=question;
         this.text= text;
      }
     public Reponse(int id,String text) {
          this.id=id ;
         this.text= text;
    }
    public Reponse(String text) {
      this.text= text;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Medecin getMedecin() {
        return this.medecin;
    }
    
    public void setMedecin(Medecin medecin) {
        this.medecin = medecin;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        return "Reponse{" + "id=" + id + ", medecin=" + medecin + ", question=" + question + ", text=" + text + '}';
    }




}


