package com.codeit.myapp.entities;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer id;
     private Laboratoire laboratoire;
     private Medecin medecin;
     private String title;
     private Date start;
     private Date end;
     private String description;
     private boolean dayoff;
     private Integer rendezvous;

    public Event() {
    }

	
    public Event(String title, Date start, Date end, boolean dayoff) {
        this.title = title;
        this.start = start;
        this.end = end;
        this.dayoff = dayoff;
    }
    public Event(Laboratoire laboratoire, Medecin medecin, String title, Date start, Date end, String description, boolean dayoff, Integer rendezvous) {
       this.laboratoire = laboratoire;
       this.medecin = medecin;
       this.title = title;
       this.start = start;
       this.end = end;
       this.description = description;
       this.dayoff = dayoff;
       this.rendezvous = rendezvous;
    }
   public Event(int id,Laboratoire laboratoire, Medecin medecin, String title, Date start, Date end, String description, boolean dayoff, Integer rendezvous) {
        this.id =id;
       this.laboratoire = laboratoire;
       this.medecin = medecin;
       this.title = title;
       this.start = start;
       this.end = end;
       this.description = description;
       this.dayoff = dayoff;
       this.rendezvous = rendezvous;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Laboratoire getLaboratoire() {
        return this.laboratoire;
    }
    
    public void setLaboratoire(Laboratoire laboratoire) {
        this.laboratoire = laboratoire;
    }
    public Medecin getMedecin() {
        return this.medecin;
    }
    
    public void setMedecin(Medecin medecin) {
        this.medecin = medecin;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isDayoff() {
        return this.dayoff;
    }
    
    public void setDayoff(boolean dayoff) {
        this.dayoff = dayoff;
    }
    public Integer getRendezvous() {
        return this.rendezvous;
    }
    
    public void setRendezvous(Integer rendezvous) {
        this.rendezvous = rendezvous;
    }




}


