package com.codeit.myapp.entities;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medecin generated by hbm2java
 */
public class Medecin implements java.io.Serializable {

    private int id;
    private Specialite specialite;
    private User user;
    private String nom;
    private String prenom;
    private String sexe;
    private Date horaireDebut;
    private Date horaireFin;
    private int numService;
    private Integer note;
    private Set events = new HashSet(0);
    private Set rendezvouses = new HashSet(0);
    private Set dossiers = new HashSet(0);
    private Set reponses = new HashSet(0);

    public Medecin() {
    }

    public Medecin(Specialite specialite, User user, String nom, String prenom, String sexe, Date horaireDebut, Date horaireFin, int numService) {
        this.specialite = specialite;
        this.user = user;
        this.nom = nom;
        this.prenom = prenom;
        this.sexe = sexe;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
        this.numService = numService;
    }

    public Medecin(Specialite specialite, User user, String nom, String prenom, String sexe, Date horaireDebut, Date horaireFin, int numService, Integer note, Set events, Set rendezvouses, Set dossiers, Set reponses) {
        this.specialite = specialite;
        this.user = user;
        this.nom = nom;
        this.prenom = prenom;
        this.sexe = sexe;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
        this.numService = numService;
        this.note = note;
        this.events = events;
        this.rendezvouses = rendezvouses;
        this.dossiers = dossiers;
        this.reponses = reponses;
    }

    public Medecin(int id, Specialite specialite, User user, String nom, String prenom, String sexe, Date horaireDebut, Date horaireFin, int numService) {
        this.id = id;
        this.specialite = specialite;
        this.user = user;
        this.nom = nom;
        this.prenom = prenom;
        this.sexe = sexe;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
        this.numService = numService;
    }

    public Medecin(int id, User user, String nom, String prenom, String sexe, Date horaireDebut, Date horaireFin, int numService) {
        this.id = id;
        this.user = user;
        this.nom = nom;
        this.prenom = prenom;
        this.sexe = sexe;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
        this.numService = numService;
    }

    public Medecin(int id, User user, Date horaireDebut, Date horaireFin, int numService) {
        this.id = id;
        this.user = user;
        this.horaireDebut = horaireDebut;
        this.horaireFin = horaireFin;
        this.numService = numService;
    }

    @Override
    public String toString() {
        return "Dr " + this.getNom() + " " + this.getPrenom();
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Specialite getSpecialite() {
        return this.specialite;
    }

    public void setSpecialite(Specialite specialite) {
        this.specialite = specialite;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getSexe() {
        return this.sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public Date getHoraireDebut() {
        return this.horaireDebut;
    }

    public void setHoraireDebut(Date horaireDebut) {
        this.horaireDebut = horaireDebut;
    }

    public Date getHoraireFin() {
        return this.horaireFin;
    }

    public void setHoraireFin(Date horaireFin) {
        this.horaireFin = horaireFin;
    }

    public int getNumService() {
        return this.numService;
    }

    public void setNumService(int numService) {
        this.numService = numService;
    }

    public Integer getNote() {
        return this.note;
    }

    public void setNote(Integer note) {
        this.note = note;
    }

    public Set getEvents() {
        return this.events;
    }

    public void setEvents(Set events) {
        this.events = events;
    }

    public Set getRendezvouses() {
        return this.rendezvouses;
    }

    public void setRendezvouses(Set rendezvouses) {
        this.rendezvouses = rendezvouses;
    }

    public Set getDossiers() {
        return this.dossiers;
    }

    public void setDossiers(Set dossiers) {
        this.dossiers = dossiers;
    }

    public Set getReponses() {
        return this.reponses;
    }

    public void setReponses(Set reponses) {
        this.reponses = reponses;
    }

}
