package com.codeit.myapp.entities;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {

 private Integer id;
    private Patient patient;
    private Specialite specialite;
    private String text;
    private Set reponses = new HashSet(0);

    public Question() {
    }

    public Question(Integer id, Patient patient, Specialite specialite, String text) {
        this.id = id;
        this.patient = patient;
        this.specialite = specialite;
        this.text = text;
    }

    public Question(Patient patient, Specialite specialite, String text) {
        this.patient = patient;
        this.specialite = specialite;
        this.text = text;
    }

    public Question(Patient patient, Specialite specialite, String text, Set reponses) {
        this.patient = patient;
        this.specialite = specialite;
        this.text = text;
        this.reponses = reponses;
    }

    public Question(String text) {
        this.text = text;
    }

    public Question(int id, String text) {
        this.id = id;
        this.text = text;

    }

    public Question(Specialite sp, String text) {
        this.specialite = sp;
        this.text = text;

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Patient getPatient() {
        return this.patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public Specialite getSpecialite() {
        return this.specialite;
    }

    public Integer getSpecialiteID() {
        return this.specialite.getId();
    }

    public void setSpecialite(Specialite specialite) {
        this.specialite = specialite;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Set getReponses() {
        return this.reponses;
    }

    public void setReponses(Set reponses) {
        this.reponses = reponses;
    }

    @Override
    public String toString() {
        return "Question{" + "id=" + id + ", patient=" + patient + ", specialite=" + specialite + ", text=" + text + ", reponses=" + reponses + '}';
    }

}
