package com.codeit.myapp.entities;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rendezvous generated by hbm2java
 */
public class Rendezvous  implements java.io.Serializable {


     private Integer id;
     private Laboratoire laboratoire;
     private Medecin medecin;
     private Patient patient;
     private Date date;
     private Date heure;
     private String etat;
     private Integer evaluation;

    public Rendezvous() {
    }

	
    public Rendezvous(Patient patient, Date date, Date heure, String etat) {
        this.patient = patient;
        this.date = date;
        this.heure = heure;
        this.etat = etat;
    }
    public Rendezvous(Laboratoire laboratoire, Medecin medecin, Patient patient, Date date, Date heure, String etat, Integer evaluation) {
       this.laboratoire = laboratoire;
       this.medecin = medecin;
       this.patient = patient;
       this.date = date;
       this.heure = heure;
       this.etat = etat;
       this.evaluation = evaluation;
    }
   public Rendezvous(int id,Laboratoire laboratoire, Medecin medecin, Patient patient, Date date, Date heure, String etat, Integer evaluation) {
        this.id= id;
        this.laboratoire = laboratoire;
        this.medecin = medecin;
        this.patient = patient;
        this.date = date;
        this.heure = heure;
        this.etat = etat;
        this.evaluation = evaluation;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Laboratoire getLaboratoire() {
        return this.laboratoire;
    }
    
    public void setLaboratoire(Laboratoire laboratoire) {
        this.laboratoire = laboratoire;
    }
    public Medecin getMedecin() {
        return this.medecin;
    }
    
    public void setMedecin(Medecin medecin) {
        this.medecin = medecin;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getHeure() {
        return this.heure;
    }
    
    public void setHeure(Date heure) {
        this.heure = heure;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }
    public Integer getEvaluation() {
        return this.evaluation;
    }
    
    public void setEvaluation(Integer evaluation) {
        this.evaluation = evaluation;
    }




}


