package com.codeit.myapp.entities;
// Generated 14 avr. 2021 00:12:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ResetPasswordRequest generated by hbm2java
 */
public class ResetPasswordRequest  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String selector;
     private String hashedToken;
     private Date requestedAt;
     private Date expiresAt;

    public ResetPasswordRequest() {
    }

    public ResetPasswordRequest(User user, String selector, String hashedToken, Date requestedAt, Date expiresAt) {
       this.user = user;
       this.selector = selector;
       this.hashedToken = hashedToken;
       this.requestedAt = requestedAt;
       this.expiresAt = expiresAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getSelector() {
        return this.selector;
    }
    
    public void setSelector(String selector) {
        this.selector = selector;
    }
    public String getHashedToken() {
        return this.hashedToken;
    }
    
    public void setHashedToken(String hashedToken) {
        this.hashedToken = hashedToken;
    }
    public Date getRequestedAt() {
        return this.requestedAt;
    }
    
    public void setRequestedAt(Date requestedAt) {
        this.requestedAt = requestedAt;
    }
    public Date getExpiresAt() {
        return this.expiresAt;
    }
    
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }




}


